# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kennyyi/Statsig/c-server-sdk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kennyyi/Statsig/c-server-sdk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kennyyi/Statsig/c-server-sdk/CMakeFiles /Users/kennyyi/Statsig/c-server-sdk//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kennyyi/Statsig/c-server-sdk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Statsig

# Build rule for target.
Statsig: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Statsig
.PHONY : Statsig

# fast build rule for target.
Statsig/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/build
.PHONY : Statsig/fast

#=============================================================================
# Target rules for targets named test_statsig

# Build rule for target.
test_statsig: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_statsig
.PHONY : test_statsig

# fast build rule for target.
test_statsig/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_statsig.dir/build.make CMakeFiles/test_statsig.dir/build
.PHONY : test_statsig/fast

src/client.o: src/client.cpp.o
.PHONY : src/client.o

# target to build an object file
src/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/client.cpp.o
.PHONY : src/client.cpp.o

src/client.i: src/client.cpp.i
.PHONY : src/client.i

# target to preprocess a source file
src/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/client.cpp.i
.PHONY : src/client.cpp.i

src/client.s: src/client.cpp.s
.PHONY : src/client.s

# target to generate assembly for a file
src/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/client.cpp.s
.PHONY : src/client.cpp.s

src/evaluator.o: src/evaluator.cpp.o
.PHONY : src/evaluator.o

# target to build an object file
src/evaluator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/evaluator.cpp.o
.PHONY : src/evaluator.cpp.o

src/evaluator.i: src/evaluator.cpp.i
.PHONY : src/evaluator.i

# target to preprocess a source file
src/evaluator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/evaluator.cpp.i
.PHONY : src/evaluator.cpp.i

src/evaluator.s: src/evaluator.cpp.s
.PHONY : src/evaluator.s

# target to generate assembly for a file
src/evaluator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/evaluator.cpp.s
.PHONY : src/evaluator.cpp.s

src/network.o: src/network.cpp.o
.PHONY : src/network.o

# target to build an object file
src/network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/network.cpp.o
.PHONY : src/network.cpp.o

src/network.i: src/network.cpp.i
.PHONY : src/network.i

# target to preprocess a source file
src/network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/network.cpp.i
.PHONY : src/network.cpp.i

src/network.s: src/network.cpp.s
.PHONY : src/network.s

# target to generate assembly for a file
src/network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/network.cpp.s
.PHONY : src/network.cpp.s

src/statsig.o: src/statsig.cpp.o
.PHONY : src/statsig.o

# target to build an object file
src/statsig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/statsig.cpp.o
.PHONY : src/statsig.cpp.o

src/statsig.i: src/statsig.cpp.i
.PHONY : src/statsig.i

# target to preprocess a source file
src/statsig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/statsig.cpp.i
.PHONY : src/statsig.cpp.i

src/statsig.s: src/statsig.cpp.s
.PHONY : src/statsig.s

# target to generate assembly for a file
src/statsig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/statsig.cpp.s
.PHONY : src/statsig.cpp.s

src/store.o: src/store.cpp.o
.PHONY : src/store.o

# target to build an object file
src/store.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/store.cpp.o
.PHONY : src/store.cpp.o

src/store.i: src/store.cpp.i
.PHONY : src/store.i

# target to preprocess a source file
src/store.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/store.cpp.i
.PHONY : src/store.cpp.i

src/store.s: src/store.cpp.s
.PHONY : src/store.s

# target to generate assembly for a file
src/store.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/store.cpp.s
.PHONY : src/store.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statsig.dir/build.make CMakeFiles/Statsig.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

tests/test-initialize.o: tests/test-initialize.cpp.o
.PHONY : tests/test-initialize.o

# target to build an object file
tests/test-initialize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_statsig.dir/build.make CMakeFiles/test_statsig.dir/tests/test-initialize.cpp.o
.PHONY : tests/test-initialize.cpp.o

tests/test-initialize.i: tests/test-initialize.cpp.i
.PHONY : tests/test-initialize.i

# target to preprocess a source file
tests/test-initialize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_statsig.dir/build.make CMakeFiles/test_statsig.dir/tests/test-initialize.cpp.i
.PHONY : tests/test-initialize.cpp.i

tests/test-initialize.s: tests/test-initialize.cpp.s
.PHONY : tests/test-initialize.s

# target to generate assembly for a file
tests/test-initialize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_statsig.dir/build.make CMakeFiles/test_statsig.dir/tests/test-initialize.cpp.s
.PHONY : tests/test-initialize.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Statsig"
	@echo "... test_statsig"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/evaluator.o"
	@echo "... src/evaluator.i"
	@echo "... src/evaluator.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/statsig.o"
	@echo "... src/statsig.i"
	@echo "... src/statsig.s"
	@echo "... src/store.o"
	@echo "... src/store.i"
	@echo "... src/store.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... tests/test-initialize.o"
	@echo "... tests/test-initialize.i"
	@echo "... tests/test-initialize.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

